### DISCUSSION TITLE
v2.0.0-alpha3

### DISCUSSION THREAD

**Discussion by mosajjal** [mosajjal/sniproxy#43] [Announcements]
sniproxy v2 now has an official alpha release! there are a lot of changes since v1 and even since a few commits ago in v2. native DoH support is here! 

Test and provide feedback. I'm sure this release is buggy af

**Comment by prooshani** [comment]
Ok, lets see what's going on here...
Soon I will update you with my results.

**Reply by prooshani** [reply]
First imapct:

- UDP, TCP and TLS works OK. Returning SNI ipv4 of server.
- HTTPS:
  SNIProxy's log:
  ``` 
  level=INFO msg="establishing connection" service=https remote=xx.xx.xx.xx:443 source=xx.xx.xx.xx:57015 host=my.domain.com
  WARN msg="response for query 770 was truncated. consider using a different protocol (TCP) for large queries" service=https
  level=ERROR msg="Finished parsing the Extension block without finding an SN block" service=https
  ```
  DNS Client's log:
   ```
   Error! DnsClient failed to resolve the request 'facebook.com. A IN': request timed out.
   ```
   
- Quic:
  SNIProxy's log:
  ```
  level=info msg="DNS query unpack: dns: bad rdata"
  level=INFO msg="returned sniproxy address for domain" service=dns fqdn=.
  level=ERROR msg="dns: overflowing header size" service=dns
  level=warning msg="QUIC stream accept: timeout: no recent network activity" 
  ```
 DNS Client's log:

  ```
  Error! Attempted to read past the end of the stream.
 ```

**Reply by prooshani** [reply]
This is the DoH settings part of config.defaults.yaml:

```
override:
    enabled: false
    # priority of the override filter. lower priority means it's checked first. if multiple filters have the same priority, they're checked in random order
    priority: 40
    # override rules. unlike others, this one does not require a path to a file. it's a map of FQDNs wildcards to IPs and ports. only HTTPS is supported
    # currently, these rules are checked with a simple for loop and string matching,
    # so it's not suited for a large number of rules. if you have a big list of rules
    # use a reverse proxy in front of sniproxy rather than using sniproxy as a reverse proxy
    rules:
      "one.one.one.one": "1.1.1.1:443"
      "google.com": "8.8.8.8:443"
    # enable listening on DoH on a specific SNI. example: "myawesomedoh.example.com". empty disables it. If you need DoH to be enabled and don't want
    # any other overrides, enable this ACL with empty rules. DoH SNI will add a default rule and start. 
    doh_sni: "my.domain.com"
    # Path to the certificate for handling tls decryption. eg: /tmp/mycert.pem
    tls_cert: /etc/letsencrypt/live/my.domain.com/fullchain.pem
    # Path to the certificate key handling tls decryption. eg: /tmp/mycert.key
    tls_key: /etc/letsencrypt/live/my.domain.com/privkey.pem

```

**Reply by prooshani** [reply]
This is general part of config file:

```
general:
  # Upsteam DNS URI. examples: Upstream DNS URI. examples: udp://1.1.1.1:53, tcp://1.1.1.1:53, tcp-tls://1.1.1.1:853, https://dns.google/dns-query
  upstream_dns: udp://8.8.8.8:53
  # Use a SOCKS proxy for upstream HTTP/HTTPS traffic. Example: socks5://admin:
  upstream_socks5:
  # DNS Port to listen on. Should remain 53 in most cases
  bind_dns_over_udp: "0.0.0.0:53"
  # enable DNS over TCP. empty disables it. example: "127.0.0.1:53"
  bind_dns_over_tcp: "0.0.0.0:53"
  # enable DNS over TLS. empty disables it. example: "127.0.0.1:853"
  bind_dns_over_tls: "0.0.0.0:853"
  # enable DNS over QUIC. empty disables it. example: "127.0.0.1:8853"
  bind_dns_over_quic: "0.0.0.0:853"
  # Path to the certificate for DoH, DoT and DoQ. eg: /tmp/mycert.pem
  tls_cert: /etc/letsencrypt/live/my.domain.com/fullchain.pem
  # Path to the certificate key for DoH, DoT and DoQ. eg: /tmp/mycert.key
  tls_key: /etc/letsencrypt/live/my.domain.com/privkey.pem
  # HTTP Port to listen on. Should remain 80 in most cases
  bind_http: "0.0.0.0:80"
  # HTTPS Port to listen on. Should remain 443 in most cases
  bind_https: "0.0.0.0:443"
  # Enable prometheus endpoint on IP:PORT. example: 127.0.0.1:8080. Always exposes /metrics and only supports HTTP
  bind_prometheus:
  # Interface used for outbound TLS connections. uses OS prefered one if empty
  interface:
  # Public IPv4 of the server, reply address of DNS A queries
  public_ipv4: xx.xx.xx.xx
  # Public IPv6 of the server, reply address of DNS AAAA queries
  public_ipv6: xxxx::xxx:xxxx:xxxx:xxxx
  # log level for the application. choices: debug, info, warn, error
  log_level: debug

```

This is `netstat -tlnp` for the server after running the sniproxy service:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:2280            0.0.0.0:*               LISTEN      492/sshd: /usr/sbin 
tcp        0      0 127.0.0.1:33729         0.0.0.0:*               LISTEN      451/containerd      
tcp6       0      0 :::2280                 :::*                    LISTEN      492/sshd: /usr/sbin 
tcp6       0      0 :::53                   :::*                    LISTEN      11885/sniproxy      
tcp6       0      0 :::80                   :::*                    LISTEN      11885/sniproxy      
tcp6       0      0 :::443                  :::*                    LISTEN      11885/sniproxy      
tcp6       0      0 :::853                  :::*                    LISTEN      11885/sniproxy 
```

Looks like all sniproxy ports, 53 for udp & tcp, 853 for tls & quic and 443 for https are open just for ipv6.

**Reply by prooshani** [reply]
DoH start working with these inputs on override section of the settings:

```
override:
    enabled: true
    # priority of the override filter. lower priority means it's checked first. if multiple filters have the same priority, they're checked in random order
    priority: 40
    # override rules. unlike others, this one does not require a path to a file. it's a map of FQDNs wildcards to IPs and ports. only HTTPS is supported
    # currently, these rules are checked with a simple for loop and string matching,
    # so it's not suited for a large number of rules. if you have a big list of rules
    # use a reverse proxy in front of sniproxy rather than using sniproxy as a reverse proxy
    rules:
      "one.one.one.one": "1.1.1.1:443"
      "google.com": "8.8.8.8:443"
    # enable listening on DoH on a specific SNI. example: "myawesomedoh.example.com". empty disables it. If you need DoH to be enabled and don't want
    # any other overrides, enable this ACL with empty rules. DoH SNI will add a default rule and start. 
    doh_sni: "my.domain.com"
    # Path to the certificate for handling tls decryption. eg: /tmp/mycert.pem
    tls_cert: /etc/letsencrypt/live/my.domain.com/fullchain.pem
    # Path to the certificate key handling tls decryption. eg: /tmp/mycert.key
    tls_key: /etc/letsencrypt/live/my.domain.com/privkey.pem
```

On client side, if I use `https://my.domain.com` as an address for DoH resolver it will return `Page Not Found` but, if I use `my.domain.com` instead, it will resolve the requests. However, it will return the url's IP not the sni server's IP which is the expected behavior.

**Reply by mosajjal** [reply]
so in summary, looks like everything is working as expected except for DoQ upstream? 

setting DoH server is a client behavior. I think you can either set it to `https://my.domain.com/dns-query` or `my.domain.com`.

**Reply by prooshani** [reply]
It looks fine except an issue that I cannot find the root!

I am using ControlD/NextDNS/AdGuard as upstream and am able to see their queries on my panels. But, even when I use this server to resolve my queries I can barely see any log from requests sent from this server!
Also, when I set this server's ip as dns for my router, command line can resolve ip's using dig or nslookup while no page on browser can be loaded!

**Reply by prooshani** [reply]
I don't have idea what is IP in this log refers to: 
(DoH log)
`level=INFO msg="overriding destination IP" service=https ip=<nil> newip=127.0.0.1:34211`

**Reply by mosajjal** [reply]
this log is shown when an override ACL is hit. `sniproxy`'s internal DoH server is implemented as a localhost TCP connection on a random port (in your case on port 34211), this shows that ACL is working and redirecting your DoH message to DoH. This log needs will probably be in debug level in v2 rather than info. 

as for your other issue, I'd be keen to see how you get on with debugging. I'll do some real world testing against v2 as well when I get the chance.

**Reply by prooshani** [reply]
This is bizarre!
I can resolve any query on DNS client, dig from any server or client, nslookup it and etc.
I don't know what is the issue with the router DNS!? Maybe double-NAT or any other ISP level restriction.
For your reference, I have 5 DNS server on different locations to test different DNS servers and different scenarios to both make my DNS queries more secure and also defeat geo-blocking restrictions.
Yesterday, I have tried a nice combination of sniproxy as a upstream for dnsproxy ( by AdGuard )...
I let the sniproxy v2 (not this latest version with DoH) to resolve just udp queries on port 54. At the other part, for dnsproxy, just forwarded all DNS queries upstreamed to sniproxy on port 54 and activated TCP, TLS, HTTPS and Quic on their standard ports on it (DNSPROXY).
And the result was very ok! I mean, I could resolve all protocols without issue tested by DNS clients. However, the router based tests failed and I had not enough time to find the issue and today you just introduced DoH version of sniproxy v2 so I let that alone for now.
I may have some small misconfigs due to numerous scenarios I have tested recently.
I am so confused now and need to think about it more deeply.

**Reply by prooshani** [reply]
> so in summary, looks like everything is working as expected except for DoQ upstream?
> 
> setting DoH server is a client behavior. I think you can either set it to `https://my.domain.com/dns-query` or `my.domain.com`.

DoH returns real IP rather than sniproxy's IP.

**Reply by mosajjal** [reply]
> > so in summary, looks like everything is working as expected except for DoQ upstream?
> > setting DoH server is a client behavior. I think you can either set it to `https://my.domain.com/dns-query` or `my.domain.com`.
> 
> DoH returns real IP rather than sniproxy's IP.

oh yeah you're right. DoH's upstream should go back to `sniproxy`'s own DNS. this is a bug.

**Reply by mosajjal** [reply]
> this log is shown when an override ACL is hit. `sniproxy`'s internal DoH server is implemented as a localhost TCP connection on a random port (in your case on port 34211), this shows that ACL is working and redirecting your DoH message to DoH. This log needs will probably be in debug level in v2 rather than info.
> 
> as for your other issue, I'd be keen to see how you get on with debugging. I'll do some real world testing against v2 as well when I get the chance.

this is fixed in the latest commit. log is debug

**Reply by mosajjal** [reply]
> > > so in summary, looks like everything is working as expected except for DoQ upstream?
> > > setting DoH server is a client behavior. I think you can either set it to `https://my.domain.com/dns-query` or `my.domain.com`.
> > 
> > 
> > DoH returns real IP rather than sniproxy's IP.
> 
> oh yeah you're right. DoH's upstream should go back to `sniproxy`'s own DNS. this is a bug.

this should also be fixed in the latest commit.

**Reply by mosajjal** [reply]
> This is bizarre! I can resolve any query on DNS client, dig from any server or client, nslookup it and etc. I don't know what is the issue with the router DNS!? Maybe double-NAT or any other ISP level restriction. For your reference, I have 5 DNS server on different locations to test different DNS servers and different scenarios to both make my DNS queries more secure and also defeat geo-blocking restrictions. Yesterday, I have tried a nice combination of sniproxy as a upstream for dnsproxy ( by AdGuard )... I let the sniproxy v2 (not this latest version with DoH) to resolve just udp queries on port 54. At the other part, for dnsproxy, just forwarded all DNS queries upstreamed to sniproxy on port 54 and activated TCP, TLS, HTTPS and Quic on their standard ports on it (DNSPROXY). And the result was very ok! I mean, I could resolve all protocols without issue tested by DNS clients. However, the router based tests failed and I had not enough time to find the issue and today you just introduced DoH version of sniproxy v2 so I let that alone for now. I may have some small misconfigs due to numerous scenarios I have tested recently. I am so confused now and need to think about it more deeply.

this screams "midbox" and MITM of DNS in ISP level. they don't do it on any other port other than 53 so it makes sense that the issue went away when you switched ports. they also don't do it on TCP either so you might benefit from trying that out.

**Reply by prooshani** [reply]
> > This is bizarre! I can resolve any query on DNS client, dig from any server or client, nslookup it and etc. I don't know what is the issue with the router DNS!? Maybe double-NAT or any other ISP level restriction. For your reference, I have 5 DNS server on different locations to test different DNS servers and different scenarios to both make my DNS queries more secure and also defeat geo-blocking restrictions. Yesterday, I have tried a nice combination of sniproxy as a upstream for dnsproxy ( by AdGuard )... I let the sniproxy v2 (not this latest version with DoH) to resolve just udp queries on port 54. At the other part, for dnsproxy, just forwarded all DNS queries upstreamed to sniproxy on port 54 and activated TCP, TLS, HTTPS and Quic on their standard ports on it (DNSPROXY). And the result was very ok! I mean, I could resolve all protocols without issue tested by DNS clients. However, the router based tests failed and I had not enough time to find the issue and today you just introduced DoH version of sniproxy v2 so I let that alone for now. I may have some small misconfigs due to numerous scenarios I have tested recently. I am so confused now and need to think about it more deeply.
> 
> this screams "midbox" and MITM of DNS in ISP level. they don't do it on any other port other than 53 so it makes sense that the issue went away when you switched ports. they also don't do it on TCP either so you might benefit from trying that out.

Unfortunately it seems like that this is not the issue!
My router besides standard UDP DNS accepts DoT only and believe me, it still not working with SNIProxy.
I can set other premium DNS resolvers, like AdGuard or ControlD on UDP and they work well.
If the MITM or MidBox was the issue they couldn't work as well.

I could able to setup other DNS servers (Technitium to be exact) which was working well with DoT only and even I was able to open censored websites, like twitter, youtube and etc., without any VPN connection while all IP location services was located me in IR.
Netflix was loaded with Iran location, Twitter was loading Trends for Iran, youtube was showing my location and suggestion for Iran...

I think I lost my path to what I was looking for and now I am just running blindly to find my way out of this.
Anyway, I am keen to test sniproxy at any level and will not look into it as an absolute resolution for my issues for now.
I believe one day sniproxy wil be the solution for me and many others.

**Comment by mosajjal** [comment]
if your router works for ~60 seconds and stops working, but `dig` etc work fine, it could potentially be due to TCP keep-alive for the upstream DNS connection. I've fixed it a couple of times and I haven't seen the issue for a long time but couldn't hurt to rule that one out too. run `sniproxy` in debug log and see if there's any EOF or `use of closed pipe` errors popping up.

**Reply by prooshani** [reply]
I will test that.

**Reply by prooshani** [reply]
DoH stopped working with this recent commit.

SNI proxy log:
```
level=ERROR msg="Finished parsing the Extension block without finding an SN block" service=https
level=WARN msg="dns: bad rdata" service=https
```

DNS Client log:
`Error! The SSL connection could not be established, see inner exception. Received an unexpected EOF or 0 bytes from the transport stream.`

If I choose DNS Upstream rather than https type, tcp or udp for example, the output logs are:

SNI Proxy log:
`invalid DNS type "" in upstream ""
`
DNS Client Log:
`Error! Response status code does not indicate success: 503 (Service Unavailable).
`

**Reply by mosajjal** [reply]
made some changes in DoQ, DoH and ACLs. it should be more stable now. check plese :)

**Comment by holygrolli** [comment]
thanks for you work @mosajjal 
I try to run my setup with v2.0.0-alpha3 but I am kind of lost with the setup.

First: the very basic setup seems to work! I query sniproxy on port 53 for netflix.com and get successfull `level=INFO msg="returned sniproxy address for domain" service=dns fqdn=netflix.com.`
I can also curl it and get a log `level=INFO msg="establishing connection" service=https remote=54.170.196.176:443 source=xx.xx.xx.xx:61663 host=netflix.com`.

Here are my issues:
1. I set `log_level: debug` and get no debug logs, for example no info about connecting through my configured socks5 (but it works, see above)
2. I provided a domain list containing only two domains. But I always get the ip of sniproxy returned no matter what domain I configured

see here my config:
```yaml
general:
  # Upsteam DNS URI. examples: Upstream DNS URI. examples: udp://1.1.1.1:53, tcp://1.1.1.1:53, tcp-tls://1.1.1.1:853, https://dns.google/dns-query
  upstream_dns: udp://8.8.8.8:53
  # Use a SOCKS proxy for upstream HTTP/HTTPS traffic. Example: socks5://admin:
  upstream_socks5: socks5://100.80.14.76:1080
  # DNS Port to listen on. Should remain 53 in most cases
  bind_dns_over_udp: "0.0.0.0:53"
  # enable DNS over TCP. empty disables it. example: "127.0.0.1:53"
  bind_dns_over_tcp:
  # enable DNS over TLS. empty disables it. example: "127.0.0.1:853"
  bind_dns_over_tls:
  # enable DNS over QUIC. empty disables it. example: "127.0.0.1:8853"
  bind_dns_over_quic:
  # Path to the certificate for DoH, DoT and DoQ. eg: /tmp/mycert.pem
  tls_cert:
  # Path to the certificate key for DoH, DoT and DoQ. eg: /tmp/mycert.key
  tls_key:
  # HTTP Port to listen on. Should remain 80 in most cases
  bind_http: "0.0.0.0:80"
  # HTTPS Port to listen on. Should remain 443 in most cases
  bind_https: "0.0.0.0:443"
  # Enable prometheus endpoint on IP:PORT. example: 127.0.0.1:8080. Always exposes /metrics and only supports HTTP
  bind_prometheus:
  # Interface used for outbound TLS connections. uses OS prefered one if empty
  interface:
  # Public IPv4 of the server, reply address of DNS A queries
  public_ipv4:
  # Public IPv6 of the server, reply address of DNS AAAA queries
  public_ipv6:
  # log level for the application. choices: debug, info, warn, error
  log_level: debug

acl:
  geoip:
    enabled: false
    priority: 10
    # strictly blocked countries
    blocked:
    # allowed countries
    allowed:
    # Path to the MMDB file. eg: /tmp/Country.mmdb, https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
    path:
    # Interval to re-fetch the MMDB file
    refresh_interval: 24h0m0s
  # domain filtering
  domain:
    enabled: true # false means ALL domains will be allowed to go through the proxy
    # priority of the domain filter. lower priority means it's checked first. if multiple filters have the same priority, they're checked in random order
    priority: 20
    # Path to the domain list. eg: /tmp/domainlist.csv. Look at the example file for the format.
    path: /root/sniproxy/domains.csv
    # Interval to re-fetch the domain list
    refresh_interval: 0h2m0s
  # IP/CIDR filtering
  cidr:
    enabled: false
    # priority of the cidr filter. lower priority means it's checked first. if multiple filters have the same priority, they're checked in random order
    priority: 30
    # Path to the CIDR list. eg: /tmp/cidr.csv. Look at the example file for the format.
    path:
    # Interval to re-fetch the domain list
    refresh_interval: 1h0m0s
  # FQDN override. This ACL is used to override the destination IP to not be the one resolved by the upstream DNS or the proxy itself, rather a custom IP and port
  # if the destination is HTTP, it uses tls_cert and tls_key certificate to terminate the original connection.
  override:
    enabled: false
    # priority of the override filter. lower priority means it's checked first. if multiple filters have the same priority, they're checked in random order
    priority: 40
```

the domain.csv only contains two entries:
```yaml
netflix.com.,suffix
netflix.de,suffix
```

any ideas?
