### ISSUE TITLE
[FeatureRequest] IP ACL

### ISSUE THREAD

**Issue by Seji64** [mosajjal/sniproxy#35]
Hi,

first of all - thanks for your effort and the great tool!

Would it be possible to add an acl feature so where we can specify a netmask which is allwed to "use"/query sniproxy.

Thefore you already logging the (client) ip which is asking, it should probably no problem to just close/reject the connection?

Commandline parameter could be something like:

`.\sniproxy --acl 192.168.0.0/32`

kind regards

seji

**Comment by mosajjal** [comment]
Hi. 

Thanks :) glad you enjoy using it. 

does this ACL offer anything that `iptables/nftables` don't offer? eg:

```
sudo iptables -A INPUT -s 192.168.0.0/16 -p tcp -m multiport --dports 80,443,53 -j ACCEPT
sudo iptables -A INPUT -s 192.168.0.0/16 -p udp --dport 53 -j ACCEPT
```

**Comment by Seji64** [comment]
In a VM/BareMetal yes, in a Container it is getting complicated...

**Comment by mosajjal** [comment]
eiter way, I'm assuming you're trying to limit incoming IPs from the internet or local network, so putting iptables on the host works

```


            internet
                │
                │
                │
                │
                │
                │
                │
                │
                │
                │
      ┌─────────┼──────────┐
   ┌──┼─────────┼──────────┼──┐
   │  │         │          │  │iptables
   └──┼─────────┼──────────┼──┘
      │         │          │
      │    ┌────▼─────┐    │
      │    │          │    │
      │    │          │    │
      │    │          │    │
      │    │          │    │
      │    │          │    │
      │    └──────────┘    │
      │      container     │
      └────────────────────┘
              host
```

**Comment by Seji64** [comment]
The principle is clear to me. Of course I can run iptables on the host and not in the container itself. However, as I understand it, you don't want to implement the feature or are reluctant to do so. Which is ok - after all it's your project and code.

**Comment by mosajjal** [comment]
It's more about potentially creating more complexity in the code itself. I'm planning a bit of overhaul and introduce a plugin system so allow/blocking requests is modular. this is a good candidate to push that through. I'll tag this as v2 and track it for that.

**Comment by mosajjal** [comment]
sniproxy v2 will be overhauled and won't have command line options anymore. only way to configure is to use `yaml`. just pushed a basic CIDR ACL to it. have a look here:

https://github.com/mosajjal/sniproxy/tree/v2

would appreciate some thorough testing of v2 from you guys :)

**Comment by prooshani** [comment]
> sniproxy v2 will be overhauled and won't have command line options anymore. only way to configure is to use `yaml`. just pushed a basic CIDR ACL to it. have a look here:
> 
> https://github.com/mosajjal/sniproxy/tree/v2
> 
> would appreciate some thorough testing of v2 from you guys :)

I would love to check the v2 of sniproxy. However, there is an error in installation at line 75 of install.sh:

```
# download the default config
wget -O /opt/sniproxy/sniproxy.yaml https://raw.githubusercontent.com/mosajjal/sniproxy/master/config.defaults.yaml 
```

This is pointing to a file which is not available and this line should be like this to work:

```
# download the default config
wget -O /opt/sniproxy/sniproxy.yaml https://raw.githubusercontent.com/mosajjal/sniproxy/v2/config.defaults.yaml 
```

You should check url's from master branch to be changed correctly to point to v2 branch for install.sh file to work.

Thanks for your nice job.

**Comment by mosajjal** [comment]
aah yep you're right :) I'll try to change it ASAP

**Comment by prooshani** [comment]
> aah yep you're right :) I'll try to change it ASAP

Thanks for the efforts.

This happened at your install.sh from master branch, as I said before.
From line 111 to 116, the TLS certificate has issue generating correct flag:

```
...
    # if any of the paths are empty, omit both arguments and print a warning for self-signed certificates
    if [ -z "$certPath" ] || [ -z "$keyPath" ]; then
        echo "WARNING: Using self-signed certificates"
    else
        execCommand="$execCommand --certPath $certPath --keyPath $keyPath"
    fi
...
```

It would be something like this:

```
...
    # if any of the paths are empty, omit both arguments and print a warning for self-signed certificates
    if [ -z "$tlsCert" ] || [ -z "$tlsKey" ]; then
        echo "WARNING: Using self-signed certificates"
    else
        execCommand="$execCommand --tlsCert $tlsCert --tlsKey $tlsKey"
    fi
...
```

Otherwise, after installation the setup will not start due to unknown flag error.

Thanks

**Comment by prooshani** [comment]
> are you talking about `install.sh` in the `master` branch or `v2`? because v2's like 116 doesn't look like what you pasted
> 
> https://github.com/mosajjal/sniproxy/blob/30c6b9818b81fd054c9b1b3f8eb2238fcb225bf2/install.sh#L117

As I told earlier, this is about install.sh from MASTER branch.
I am aware that v2 config has been changed completely and from v2 all settings will fit in a YAML file which looks much more professional and easier to maintain and use.

**Comment by mosajjal** [comment]
oh I see what you mean. yeah there are some bugs here and there for v1. I'll try to fix them but mostly keen to move people off of v1 asap. how's v2 experience so far?

**Comment by prooshani** [comment]
> oh I see what you mean. yeah there are some bugs here and there for v1. I'll try to fix them but mostly keen to move people off of v1 asap. how's v2 experience so far?

Ok, I got the point but this small issues can be resolved fast and even in your archive you need version which would work or soon you will have a bunch of versions/commits which don't have idea if that was the working or buggy ones.

> how's v2 experience so far?

The installation fixed but TLS cert and key will not supply through the interactive installation. I have checked several times and am pretty sure the URI of the key and cert files are correct but the installation won't accept them.
The current work around is to bypass this steps on installation and afterwards change it through the config yaml file.

Anyway, I am receiving an Error:

`level=ERROR msg="failed to parse config file" err="invalid character 'g' looking for beginning of value"`

Do you think this is something about the config file, which starts with `general` ?

**Comment by mosajjal** [comment]
yep agreed. I'll try to backport enough fixes to keep it running. I guess not many people (including myself) were using certificates :) 

as for v2's error, can you please share your `config.yaml`

**Comment by prooshani** [comment]
> yep agreed. I'll try to backport enough fixes to keep it running. I guess not many people (including myself) were using certificates :)
> 
> as for v2's error, can you please share your `config.yaml`

Sure,

```
general:
  # Bind 443 and 80 to a Specific IP Address. Doesn't apply to DNS Server. DNS Server always listens on 0.0.0.0
  bind_ip: 0.0.0.0
  # Upsteam DNS URI. examples: Upstream DNS URI. examples: udp://1.1.1.1:53, tcp://1.1.1.1:53, tcp-tls://1.1.1.1:853, https://dns.google/dns-query
  upstream_dns: tls://xx.dnsresolver.com:853
  # Use a SOCKS proxy for upstream HTTP/HTTPS traffic. Example: socks5://admin:
  upstream_socks5:
  # enable DNS over TCP as well as UDP
  bind_dns_over_tcp: true
  # enable DNS over TLS as well as UDP
  bind_dns_over_tls: true
  # enable DNS over QUIC as well as UDP
  bind_dns_over_quic: true
  # Path to the certificate for DoH, DoT and DoQ. eg: /tmp/mycert.pem
  tls_cert:/etc/letsencrypt/live/mydomain.com/fullchain.pem
  # Path to the certificate key for DoH, DoT and DoQ. eg: /tmp/mycert.key
  tls_key:/etc/letsencrypt/live/mydomain.com/privkey.pem
  # DNS Port to listen on. Should remain 53 in most cases
  dns_port: 53
  # HTTP Port to listen on. Should remain 80 in most cases
  http_port: 80
  # HTTPS Port to listen on. Should remain 443 in most cases
  https_port: 443
  # Interface used for outbound TLS connections. uses OS prefered one if empty
#  tls_port: 853
 interface:
  # Public IPv4 of the server, reply address of DNS A queries
  public_ipv4:xx.xx.xx.xx
  # Public IPv6 of the server, reply address of DNS AAAA queries
  public_ipv6:xx::xx:xx:xx:xx
  # Enable Reverse Proxy for a specific FQDN and upstream URL. example: www.example.com::http://127.0.0.1:4001
  reverse_proxy:
  # Path to the certificate for reverse proxy. eg: /tmp/mycert.pem
  reverse_proxy_cert:
  # Path to the certificate key for reverse proxy. eg: /tmp/mycert.key
  reverse_proxy_key:
  # Enable prometheus endpoint on IP:PORT. example: 127.0.0.1:8080. Always exposes /metrics and only supports HTTP
  prometheus:
  # log level for the application. choices: debug, info, warn, error
  log_level: debug
acl:
  # Enable geoip filtering
  geoip:
    enabled: false
    # Exclude countries to be allowed to connect. example: US,CA
    exclude:
    # Include countries to be allowed to connect. example: US,CA
    include:
    # Path to the MMDB file. eg: /tmp/Country.mmdb, https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
    path:
    # Interval to re-fetch the MMDB file
    refresh_interval: 24h0m0s
  # Enable domain filtering
  domain:
    enabled: false # false means ALL domains will be allowed to go through the proxy
    # Path to the domain list. eg: /tmp/domainlist.csv. Look at the example file for the format.
    path:
    # Interval to re-fetch the domain list
    refresh_interval: 1h0m0s
  # Enable IP ACL
  cidr:
    enabled: false
    # Path to the CIDR list. eg: /tmp/cidr.csv. Look at the example file for the format.
    path:
    # Interval to re-fetch the domain list
    refresh_interval: 1h0m0s

```

New outcomes from v2 test:
Now, it is working ok except that It cannot resolve DoT, DoH, DNS-over-TCP and DoQ.
It is now only resolving UDP requests successfully.
